---
title: "04M09_2 STIC Summary"
author: "Christopher Wheeler"
date: '2022-09-08'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bring in processed STIC data frame

```{r import}
library(tidyverse)
STIC_KNZ_04M09_00_LS <- read_csv("STIC_KNZ_04M09_00_LS.csv")

STIC_KNZ_04M09_00_LS$field_SpC <- as.numeric(STIC_KNZ_04M09_00_LS$field_SpC)

STIC_KNZ_04M09_00_LS[17950, 16] <- 572

head(STIC_KNZ_04M09_00_LS)
```

## Time series of SpC colored by wet/dry designation (red dot represents field SpC measurement)

```{r Spc time series}
ggplot(STIC_KNZ_04M09_00_LS, aes(x = datetime, y = SpC, color = wetdry, group = 1)) + 
  geom_path(size = 0.7) + 
  geom_point(aes(x = datetime, y = field_SpC), size = 3, color = "red") +
   theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black", size = 1)) + 
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14))
```

## Time series of Temperature (C) recorded by STIC

```{r temp time series}
ggplot(STIC_KNZ_04M09_00_LS, aes(x = datetime, y = tempC)) + 
  geom_path() + 
  geom_smooth(color = "steelblue", se = FALSE) +
   theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black", size = 1)) + 
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14))
```

## Map of STIC location

```{r STIC location map}
library(Rcpp)
library(sp)
library(raster)
library(rgdal)
library(rasterVis)
library(sf)

# Bring in stream line shape files
konza_streams <- st_read("GIS210/GIS210.shp")

stic_location <- st_as_sf(STIC_KNZ_04M09_00_LS,
                                coords = c("long", "lat"), 
                                crs = 4326)

ggplot() + 
  geom_sf(data = konza_streams) + 
  geom_sf(data = stic_location, size = 3, color = "red") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black", size = 1)) + 
  theme(axis.text = element_text(size = 9),
        axis.title = element_text(size = 12)) +
  xlab("Longitude") + 
  ylab("Latitude") + 
  coord_sf(xlim = c(708000.9  , 710500.3 ), ylim = c(4327200.8  , 4330000.0 ), expand = FALSE)
```

## Scatterplot of STIC-measured SpC values versus YSI field measuremnts 
still need to make



