# STIC_03_CombineData.R
# Script to combine all QAQCed data from each site. It produces a single output
# CSV file and a single output plot for each site.

### IMPORTANT:
### IF ANY HAND-EDITS ARE NEEDED FOR DATA:
###  - MAKE THEM DIRECTLY IN THE OUTPUT FILES GENERATED BY STIC_02_QAQCdata.R 
###  - NOTE THE EDITS IN THE [site]_STIC_QAQC_ManualChanges.xlsx FILE
###  - THEN RUN THIS SCRIPT
###    (you can rerun the script if you notice something wrong and make an additional change)

# load control script
source("STIC_00_ControlScript.R")

# load in metadata 
metadata <- read_csv(path_observations)

# Get list of file paths from the folder
#fs::dir_ls(dir_data_qaqc)
stic_file_list <- fs::dir_ls(dir_data_qaqc, regexp = "\\.csv$")

### using the map_dfr function to loop in individual
# files from the folder, then row bind
stic_data_classified <- stic_file_list |> 
  map_dfr(read_csv) |> 
  mutate(siteID = as_factor(siteID))

# define plot limits so all plots have the same time period
first_date <- ymd_hms("2021-03-01 00:00:00")
last_date <- ymd_hms("2024-06-01 00:00:00") # make it a bit after the last date for last download

## split up into files for each site and plot
all_sites <- unique(stic_data_classified$siteID)
for (i in 1:length(all_sites)){
  ## save combined CSV file
  # get data from site
  s <- all_sites[i]
  df_s <- subset(stic_data_classified, siteID == s)
  write_csv(df_s, file.path(dir_data_combined, paste0(s, ".csv")))
  
  ## make combined QAQC plot
  
  # extract start/end dates of each download period
  s_reps <- unique(df_s$rep)
  s_reps_dates <- ymd_hms(paste0(unlist(strsplit(s_reps, "-")), " 12:00:00"))
  
  # get metadata from site
  meta_s <- 
    metadata |> 
    filter(Location == s) |> 
    mutate(datetime = lubridate::mdy_hm(datetime))
  
  # make QAQC graph
  p_s <-
    df_s |> 
    select(datetime, condUncal, tempC, SpC, wetdry) |> 
    pivot_longer(cols = c(condUncal, tempC, SpC), names_to = "variable") |> 
    ggplot() + 
    geom_point(aes(x = datetime, y = value, color = wetdry)) + 
    facet_wrap(~variable, scales = "free_y", ncol = 1) +
    geom_vline(xintercept = subset(meta_s, wet_dry == "wet")$datetime, color = "blue") +
    geom_vline(xintercept = subset(meta_s, wet_dry == "dry")$datetime, color = "red") +
    geom_vline(xintercept = subset(meta_s, wet_dry == "damp")$datetime, color = "green") +
    geom_vline(xintercept = s_reps_dates, color = "black", linetype = "dashed") +
    scale_x_datetime(limits = c(first_date, last_date)) +
    scale_color_manual(values = c("wet" = "#0082c8", "dry" = "#e6194b")) +
    labs(title = s,
         subtitle = "Vertical lines:\nBlue=wet obs, Red=dry obs, Green=damp obs\nBlack dashed=start/end of download period") + 
    theme_bw() +
    theme(legend.position = "bottom")
  ggsave(file.path(dir_plots_combined, paste0(s, ".png")), 
         p_s, width = 190, height = 225, units = "mm")
  
  print(paste0(i, " of ", length(all_sites), " complete, ", Sys.time()))
}

# set mode function
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

## visualize results
stic_data_daily <-
  stic_data_classified |> 
  mutate(day = as.Date(datetime),
         site_subloc = paste0(siteID, "_", sublocation)) |> 
  group_by(day, site_subloc) |> 
  summarize(prc_data = sum(wetdry %in% c("wet", "dry"))/n(),
            prc_wet = sum(wetdry == "wet")/n(),
            condUncal_mean = mean(condUncal, na.rm = T),
            tempC_mean = mean(tempC, na.rm = T),
            qual_rating_mode = Mode(qual_rating))

ggplot(stic_data_daily, aes(x = day, y = site_subloc, fill = prc_wet)) +
  geom_tile() +
  scale_fill_viridis_c(direction = -1) +
  theme_bw()
ggsave(file.path(dir_plots_combined, "_AllSites_PrcWet.png"),
       height = 240, width = 190, units = "mm")

ggplot(stic_data_daily, aes(x = day, y = site_subloc, fill = condUncal_mean)) +
  geom_tile() +
  scale_fill_viridis_c(direction = -1) +
  theme_bw()
ggsave(file.path(dir_plots_combined, "_AllSites_condUncal.png"),
       height = 240, width = 190, units = "mm")

ggplot(stic_data_daily, aes(x = day, y = site_subloc, fill = tempC_mean)) +
  geom_tile() +
  scale_fill_viridis_c(option = "C", limits = c(-10, 40)) +
  theme_bw()
ggsave(file.path(dir_plots_combined, "_AllSites_tempC.png"),
       height = 240, width = 190, units = "mm")

ggplot(stic_data_daily, aes(x = day, y = site_subloc, fill = qual_rating_mode)) +
  geom_tile() +
  scale_fill_viridis_d() +
  theme_bw()
ggsave(file.path(dir_plots_combined, "_AllSites_QualRating.png"),
       height = 240, width = 190, units = "mm")
